export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORY_FIELDS_VALUES_SUCCESS =
	"LOAD_CATEGORY_FIELDS_VALUES_SUCCESS";

export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
